export const GET_HOUSE_DETAIL_REQUEST = 'HouseDetail/GET_HOUSE_DETAIL_REQUEST';
export const GET_HOUSE_DETAIL_SUCCESS = 'HouseDetail/GET_HOUSE_DETAIL_SUCCESS';
export const GET_HOUSE_DETAIL_FAILED = 'HouseDetail/GET_HOUSE_DETAIL_FAILED';

export const POST_CREATE_CONVERSATION_REQUEST = 'HouseDetail/POST_CREATE_CONVERSATION_REQUEST';
export const POST_CREATE_CONVERSATION_SUCCESS = 'HouseDetail/POST_CREATE_CONVERSATION_SUCCESS';
export const POST_CREATE_CONVERSATION_FAILED = 'HouseDetail/POST_CREATE_CONVERSATION_FAILED';
export const POST_CREATE_CONVERSATION_RESET = 'HouseDetail/POST_CREATE_CONVERSATION_RESET';

export const POST_CREATE_APPOINTMENT_REQUEST = 'HouseDetail/POST_CREATE_APPOINTMENT_REQUEST';
export const POST_CREATE_APPOINTMENT_FAILED = 'HouseDetail/POST_CREATE_APPOINTMENT_FAILED';
export const POST_CREATE_APPOINTMENT_RESET = 'HouseDetail/POST_CREATE_APPOINTMENT_RESET';
