export const GET_HOUSE_DETAIL_REQUEST = 'HouseDetail/GET_HOUSE_DETAIL_REQUEST';
export const GET_HOUSE_DETAIL_SUCCESS = 'HouseDetail/GET_HOUSE_DETAIL_SUCCESS';
export const GET_HOUSE_DETAIL_FAILED = 'HouseDetail/GET_HOUSE_DETAIL_FAILED';
