export const POST_CREATE_HOUSE_REQUEST = 'HouseForm/POST_CREATE_HOUSE_REQUEST';
export const POST_CREATE_HOUSE_FAILED = 'HouseForm/POST_CREATE_HOUSE_FAILED';

export const PATCH_UPDATE_HOUSE_REQUEST = 'HouseForm/PATCH_UPDATE_HOUSE_REQUEST';
export const PATCH_UPDATE_HOUSE_FAILED = 'HouseForm/PATCH_UPDATE_HOUSE_FAILED';

export const DELETE_HOUSE_IMAGE_REQUEST = 'HouseForm/DELETE_HOUSE_IMAGE_REQUEST';
export const DELETE_HOUSE_IMAGE_FAILED = 'HouseForm/DELETE_HOUSE_IMAGE_FAILED';
