export const POST_CREATE_HOUSE_REQUEST = 'HouseForm/POST_CREATE_HOUSE_REQUEST';
export const POST_CREATE_HOUSE_SUCCESS = 'HouseForm/POST_CREATE_HOUSE_SUCCESS';
export const POST_CREATE_HOUSE_FAILED = 'HouseForm/POST_CREATE_HOUSE_FAILED';
export const POST_CREATE_HOUSE_RESET = 'HouseForm/POST_CREATE_HOUSE_RESET';

export const PATCH_UPDATE_HOUSE_REQUEST = 'HouseForm/PATCH_UPDATE_HOUSE_REQUEST';
export const PATCH_UPDATE_HOUSE_FAILED = 'HouseForm/PATCH_UPDATE_HOUSE_FAILED';
export const PATCH_UPDATE_HOUSE_RESET = 'HouseForm/PATCH_UPDATE_HOUSE_RESET';

export const DELETE_HOUSE_IMAGE_REQUEST = 'HouseForm/DELETE_HOUSE_IMAGE_REQUEST';
export const DELETE_HOUSE_IMAGE_FAILED = 'HouseForm/DELETE_HOUSE_IMAGE_FAILED';
export const DELETE_HOUSE_IMAGE_RESET = 'HouseForm/DELETE_HOUSE_IMAGE_RESET';

export const SET_STEP = 'HouseForm/SET_STEP';
export const SET_FORM_DATA = 'HouseForm/SET_FORM_DATA';
export const FORM_RESET = 'HouseForm/FORM_RESET';
