export const GET_APPOINTMENT_LIST_REQUEST = 'AppointmentList/GET_APPOINTMENT_LIST_REQUEST';
export const GET_APPOINTMENT_LIST_SUCCESS = 'AppointmentList/GET_APPOINTMENT_LIST_SUCCESS';
export const GET_APPOINTMENT_LIST_FAILED = 'AppointmentList/GET_APPOINTMENT_LIST_FAILED';

export const PATCH_UPDATE_APPOINTMENT_REQUEST = 'AppointmentList/PATCH_UPDATE_APPOINTMENT_REQUEST';
export const PATCH_UPDATE_APPOINTMENT_FAILED = 'AppointmentList/PATCH_UPDATE_APPOINTMENT_FAILED';
