export const GET_USER_DETAIL_REQUEST = 'UserDetail/GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_SUCCESS = 'UserDetail/GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILED = 'UserDetail/GET_USER_DETAIL_FAILED';

export const PATCH_UPDATE_USER_REQUEST = 'UserDetail/PATCH_UPDATE_USER_REQUEST';
export const PATCH_UPDATE_USER_FAILED = 'UserDetail/PATCH_UPDATE_USER_FAILED';

export const PATCH_CHANGE_PASSWORD_REQUEST = 'UserDetail/PATCH_CHANGE_PASSWORD_REQUEST';
export const PATCH_CHANGE_PASSWORD_FAILED = 'UserDetail/PATCH_CHANGE_PASSWORD_FAILED';
