export const GET_HOUSE_LIST_REQUEST = 'HouseList/GET_HOUSE_LIST_REQUEST';
export const GET_HOUSE_LIST_SUCCESS = 'HouseList/GET_HOUSE_LIST_SUCCESS';
export const GET_HOUSE_LIST_FAILED = 'HouseList/GET_HOUSE_LIST_FAILED';

export const DELETE_HOUSE_REQUEST = 'HouseList/DELETE_HOUSE_REQUEST';
export const DELETE_HOUSE_FAILED = 'HouseList/DELETE_HOUSE_FAILED';

export const POST_ADD_TO_FAVORITE_REQUEST = 'HouseList/POST_ADD_TO_FAVORITE_REQUEST';
export const POST_ADD_TO_FAVORITE_FAILED = 'HouseList/POST_ADD_TO_FAVORITE_FAILED';

export const DELETE_FROM_FAVORITE_REQUEST = 'HouseList/DELETE_FROM_FAVORITE_REQUEST';
export const DELETE_FROM_FAVORITE_FAILED = 'HouseList/DELETE_FROM_FAVORITE_FAILED';
