export const GET_HOUSE_LIST_REQUEST = 'HouseList/GET_HOUSE_LIST_REQUEST';
export const GET_HOUSE_LIST_SUCCESS = 'HouseList/GET_HOUSE_LIST_SUCCESS';
export const GET_HOUSE_LIST_FAILED = 'HouseList/GET_HOUSE_LIST_FAILED';

export const DELETE_HOUSE_REQUEST = 'HouseList/DELETE_HOUSE_REQUEST';
export const DELETE_HOUSE_FAILED = 'HouseList/DELETE_HOUSE_FAILED';
