export const GET_CONVERSATION_LIST_REQUEST = 'ConversationList/GET_CONVERSATION_LIST_REQUEST';
export const GET_CONVERSATION_LIST_SUCCESS = 'ConversationList/GET_CONVERSATION_LIST_SUCCESS';
export const GET_CONVERSATION_LIST_FAILED = 'ConversationList/GET_CONVERSATION_LIST_FAILED';

export const GET_CONVERSATION_DETAIL_REQUEST = 'ConversationList/GET_CONVERSATION_DETAIL_REQUEST';
export const GET_CONVERSATION_DETAIL_SUCCESS = 'ConversationList/GET_CONVERSATION_DETAIL_SUCCESS';
export const GET_CONVERSATION_DETAIL_FAILED = 'ConversationList/GET_CONVERSATION_DETAIL_FAILED';

export const POST_SEND_MESSAGE_REQUEST = 'ConversationList/POST_SEND_MESSAGE_REQUEST';
export const POST_SEND_MESSAGE_FAILED = 'ConversationList/POST_SEND_MESSAGE_FAILED';
