export const GET_USER_LIST_REQUEST = 'UserList/GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'UserList/GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILED = 'UserList/GET_USER_LIST_FAILED';

export const DELETE_USER_REQUEST = 'UserList/DELETE_USER_REQUEST';
export const DELETE_USER_FAILED = 'UserList/DELETE_USER_FAILED';
