export const GET_FAVORITE_LIST_REQUEST = 'FavoriteList/GET_FAVORITE_LIST_REQUEST';
export const GET_FAVORITE_LIST_SUCCESS = 'FavoriteList/GET_FAVORITE_LIST_SUCCESS';
export const GET_FAVORITE_LIST_FAILED = 'FavoriteList/GET_FAVORITE_LIST_FAILED';
